"""
Loom AI v2 — /api/v2/decision-registry router.

Exposes the full Decision Intelligence Registry of all 23 factory management questions.
"""
from __future__ import annotations

from typing import Any
from fastapi import APIRouter

router = APIRouter()

REGISTRY_DATA = [
    {
        "id": "Q01",
        "title": "Today's Target vs Actual Production & Efficiency",
        "question": "Today's weaving target and actual production, kilo-pick, efficiency, warp and weft breaks, actual-vs-target variance, comparison with yesterday, with suggestions.",
        "module": "Production Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "actual_picks / (std_rpm * sched_min) * 100",
        "ml_dependency": "None (Deterministic SQL & Pure Formulas)",
        "ai_role": "Management narrative explanation of target variance",
    },
    {
        "id": "Q02",
        "title": "Warp & Weft Extra Timing Analytics",
        "question": "Standard warp and weft time, extra warp/weft time used, resulting production/revenue loss, with suggestions.",
        "module": "Production Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "CALCULATED",
        "coverage_pct": 96,
        "calculation_basis": "max(actual_time - std_time, 0) * rate",
        "ml_dependency": "None (Shift timing logs)",
        "ai_role": "Highlighting chronic knotting and weft feeder delays",
    },
    {
        "id": "Q03",
        "title": "Loom & Weaver Normalized Performance Score (CPS)",
        "question": "Looms with highest/lowest production and efficiency today, best and worst performing weaver, with suggestions.",
        "module": "Production Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "CPS = 0.40*Eff + 0.30*Util + 0.15*(1-Breaks) + 0.15*TargetAch",
        "ml_dependency": "None (Normalized Multi-factor Matrix)",
        "ai_role": "Balanced shift weaver re-allocation recommendations",
    },
    {
        "id": "Q04",
        "title": "Historical Multi-Period Production Rollups",
        "question": "Weekly, monthly and yearly production by loom, with suggestions.",
        "module": "Production Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "Aggregated daily, weekly, monthly rolls by loom and style",
        "ml_dependency": "Rolling trend slope regression",
        "ai_role": "Drift detection on chronic underperforming looms",
    },
    {
        "id": "Q05",
        "title": "Highest Downtime vs Most Frequent Breakdown Looms",
        "question": "Loom with highest and lowest breakdown time today and loom with most breakdowns this month, with suggestions.",
        "module": "Breakdown Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "Bimodal split: Total stopped minutes vs StopEvent count",
        "ml_dependency": "None (StopEvent relational logs)",
        "ai_role": "Differentiating long single outages from repetitive micro-stops",
    },
    {
        "id": "Q06",
        "title": "MTTR, Pareto Root Causes & Anomaly Detection",
        "question": "Average downtime per breakdown, main breakdown reasons, abnormal breakdown patterns, with suggestions.",
        "module": "Breakdown Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "CALCULATED",
        "coverage_pct": 98,
        "calculation_basis": "Z-score = (downtime - 30d_mean) / 30d_std",
        "ml_dependency": "Statistical Anomaly Baselines (30-day window)",
        "ai_role": "Electrical vs Mechanical root-cause classification",
    },
    {
        "id": "Q07",
        "title": "Breakdown Financial Loss & Shift Breakdown Impact",
        "question": "Production and revenue lost due to breakdowns, and shift with highest breakdown time, with suggestions.",
        "module": "Breakdown Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "CALCULATED",
        "coverage_pct": 98,
        "calculation_basis": "Downtime min * standard pick rate * selling rate",
        "ml_dependency": "None (Mutually exclusive stop logs)",
        "ai_role": "Financial loss prioritization",
    },
    {
        "id": "Q08",
        "title": "Operator Attendance & Shift Distribution",
        "question": "Operators present/absent today and shift with highest and lowest attendance, with suggestions.",
        "module": "Manpower Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "Roster headcount vs Present roll-call",
        "ml_dependency": "None",
        "ai_role": "Attendance anomaly alerts",
    },
    {
        "id": "Q09",
        "title": "Weaver Efficiency Ranking & Shift Comparison",
        "question": "Operator with highest/lowest production and efficiency, shift with highest/lowest output, with suggestions.",
        "module": "Manpower Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "Weaver Index = Actual Eff / Grade Standard Eff",
        "ml_dependency": "None",
        "ai_role": "Skill upgrading and peer coaching suggestions",
    },
    {
        "id": "Q10",
        "title": "Absenteeism Effect on Production & Capacity Loss",
        "question": "Effect of absenteeism on production and production affected by manpower shortage, with suggestions.",
        "module": "Manpower Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "ESTIMATED",
        "coverage_pct": 95,
        "calculation_basis": "Shortage hours * standard looms per weaver * pick rate",
        "ml_dependency": "None",
        "ai_role": "Dynamic relief weaver allocation",
    },
    {
        "id": "Q11",
        "title": "Operator Grade & Work Allotment Optimization",
        "question": "Operator grade and work allotment, with suggestions.",
        "module": "Manpower Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "Grade standard matrix (G1 to Trainee) vs Active load",
        "ml_dependency": "None",
        "ai_role": "Workload balancing",
    },
    {
        "id": "Q12",
        "title": "Overdue & Scheduled Preventive Maintenance",
        "question": "Looms requiring maintenance, overdue maintenance, preventive maintenance, with suggestions.",
        "module": "Maintenance Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "Next PM due date delta against current date",
        "ml_dependency": "None",
        "ai_role": "Overdue work order dispatch",
    },
    {
        "id": "Q13",
        "title": "Maintenance Duration Overrun % & Recurring Issues",
        "question": "Scheduled maintenance today, extra maintenance carried out, looms with repeated maintenance issues versus standard downtime, with suggestions.",
        "module": "Maintenance Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 98,
        "calculation_basis": "max(actual_duration - scheduled_duration, 0)",
        "ml_dependency": "None",
        "ai_role": "Technician procedure review",
    },
    {
        "id": "Q14",
        "title": "ML 24h Breakdown Risk & Maintenance Cost Forecaster",
        "question": "AI prediction of potential loom breakdowns and maintenance cost by loom, with suggestions.",
        "module": "Prediction Center",
        "status": "MODEL PREDICTED",
        "data_readiness": "MODEL PREDICTED",
        "coverage_pct": 92,
        "calculation_basis": "GradientBoostedTrees_v2 classifier with rolling lag features",
        "ml_dependency": "Supervised ML (ROC-AUC 0.842, Precision 78.6%, Recall 81.4%)",
        "ai_role": "Proactive intervention work orders",
    },
    {
        "id": "Q15",
        "title": "Standard vs Actual CFM Air Consumption",
        "question": "Standard vs actual CFM consumption for each loom and looms with excessive air consumption, with suggestions.",
        "module": "Air & Compressor",
        "status": "OPERATIONAL",
        "data_readiness": "SENSOR / SENSOR FEED",
        "coverage_pct": 95,
        "calculation_basis": "max(actual_cfm - standard_cfm, 0)",
        "ml_dependency": "None",
        "ai_role": "Pneumatic leakage localization",
    },
    {
        "id": "Q16",
        "title": "Compressor Air Loss Volume & Financial Cost",
        "question": "Compressor air loss and estimated cost of air loss, with suggestions.",
        "module": "Air & Compressor",
        "status": "OPERATIONAL",
        "data_readiness": "CALCULATED",
        "coverage_pct": 95,
        "calculation_basis": "(excess_cfm / 4.5) * hours * power_tariff",
        "ml_dependency": "None",
        "ai_role": "Energy waste cost transparency",
    },
    {
        "id": "Q17",
        "title": "Air Consumption Period & Style Comparison",
        "question": "Compressor consumption comparison with last day/week/month, quality-wise and loom-wise, with suggestions.",
        "module": "Air & Compressor",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 95,
        "calculation_basis": "Multi-period aggregation by fabric construction",
        "ml_dependency": "None",
        "ai_role": "Style-wise pneumatic pressure calibration",
    },
    {
        "id": "Q18",
        "title": "Fabric Defect Percentage & Defect Cause Pareto",
        "question": "Today's fabric defect percentage, loom/style with highest defect rate, major defect causes, with suggestions.",
        "module": "Quality Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 94,
        "calculation_basis": "(defective_metres / total_inspected_metres) * 100",
        "ml_dependency": "None",
        "ai_role": "Reed alignment & warp tension tuning",
    },
    {
        "id": "Q19",
        "title": "Crimp Percentage vs Standard Crimp Tolerances",
        "question": "Standard crimp percentage and fabric with abnormal crimp percentage, with suggestions.",
        "module": "Quality Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "LAB LOG",
        "coverage_pct": 90,
        "calculation_basis": "actual_crimp_pct - std_crimp_pct",
        "ml_dependency": "None",
        "ai_role": "Take-up motion and warp tension calibration",
    },
    {
        "id": "Q20",
        "title": "Yarn Waste Percentage by Shift & Material Balance",
        "question": "Today's yarn waste percentage and shift with highest yarn waste.",
        "module": "Quality Intelligence",
        "status": "OPERATIONAL",
        "data_readiness": "MEASURED",
        "coverage_pct": 96,
        "calculation_basis": "(waste_kg / input_yarn_kg) * 100",
        "ml_dependency": "None",
        "ai_role": "Weft waste elimination and knotter inspection",
    },
    {
        "id": "Q21",
        "title": "Daily & Monthly Weaving Revenue by Loom and Style",
        "question": "Today's and monthly weaving revenue, loom/fabric style with highest and lowest revenue.",
        "module": "Revenue & Loss",
        "status": "OPERATIONAL",
        "data_readiness": "AVAILABLE",
        "coverage_pct": 100,
        "calculation_basis": "metres_produced * selling_rate_per_metre",
        "ml_dependency": "None",
        "ai_role": "High-contribution style loom prioritization",
    },
    {
        "id": "Q22",
        "title": "Net Revenue, Direct Costs & Contribution Profit",
        "question": "Today's total revenue, profit/loss and main reasons, with suggestions.",
        "module": "Revenue & Loss",
        "status": "OPERATIONAL",
        "data_readiness": "CALCULATED WITH GATING",
        "coverage_pct": 95,
        "calculation_basis": "Revenue - (Yarn + Energy + Maintenance + Labour)",
        "ml_dependency": "None",
        "ai_role": "Direct cost margin analysis",
    },
    {
        "id": "Q23",
        "title": "Revenue Loss Attribution Waterfall (Mutually Exclusive)",
        "question": "Revenue lost due to breakdowns, electrical downtime, and low efficiency, with suggestions.",
        "module": "Revenue & Loss",
        "status": "OPERATIONAL",
        "data_readiness": "CALCULATED",
        "coverage_pct": 100,
        "calculation_basis": "Mutually exclusive loss decomposition (no double counting)",
        "ml_dependency": "None",
        "ai_role": "Loss elimination roadmap",
    },
]


@router.get("/")
def get_decision_registry() -> list[dict[str, Any]]:
    return REGISTRY_DATA
