"""
Loom AI — SQLAlchemy ORM models (V1).

NOTE: This file was renamed from app/models.py to app/db_models.py
in Phase 2 when the app/models/ package was created for Pydantic schemas.
All imports should reference app.db_models, not app.models.

Design principles
-----------------
1. PROVENANCE FIRST: every fact table carries source_type and import_batch_id
   so the UI can always tell a manager whether a number came from real data,
   derived calculation, or synthetic generation.

2. EXTENSIBILITY: every future table hangs off Machine using the same
   machine_id + date + shift grain.

3. CONSTRAINTS IN THE DB: enforced at the PostgreSQL level, not only in app code.

4. NUMERIC PRECISION: revenue and quantities use Numeric (fixed-point),
   not Float, to avoid floating-point rounding surprises in financial totals.

Granularity values
------------------
  real_grounded          - machine number corresponds to a real physical machine
  synthetic_loom_number  - loom number was invented; real reports show brand totals only

Source type values
------------------
  synthetic  - generated by the synthetic data generator
  real       - imported from actual company records
  derived    - calculated from other records (e.g. revenue = qty × rate)
"""
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


# ─────────────────────────────────────────────────────────────────────────────
# Import Batch — provenance anchor for every import
# ─────────────────────────────────────────────────────────────────────────────

class ImportBatch(Base):
    """
    One record per CSV import run.

    Every imported fact row carries an import_batch_id so it is always
    traceable back to its source file and import timestamp.

    The is_demo flag is the key field for the UI's data-provenance badge:
      is_demo=True  → UI shows "Demo / Synthetic Data — values are not live measurements"
      is_demo=False → UI shows "Production Data — imported from company reports"

    The dataset_label is the human-readable string shown in the UI badge.
    """

    __tablename__ = "import_batches"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    import_timestamp: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    source_file: str = Column(String(500), nullable=False, comment="Filename of the imported CSV/Excel")
    source_type: str = Column(
        String(20),
        nullable=False,
        comment="synthetic | real | derived",
    )
    is_demo: bool = Column(
        Boolean,
        nullable=False,
        default=True,
        comment="True = synthetic/demo data. UI must display a clear warning.",
    )
    dataset_label: str = Column(
        String(100),
        nullable=True,
        comment="Human-readable label shown in the UI data-provenance badge",
    )
    notes: str = Column(Text, nullable=True)
    imported_by: str = Column(String(100), nullable=True)

    # Denormalized stats for fast UI display
    production_accepted: int = Column(Integer, nullable=False, default=0)
    production_rejected: int = Column(Integer, nullable=False, default=0)
    breakdown_accepted: int = Column(Integer, nullable=False, default=0)
    breakdown_rejected: int = Column(Integer, nullable=False, default=0)
    revenue_accepted: int = Column(Integer, nullable=False, default=0)
    revenue_rejected: int = Column(Integer, nullable=False, default=0)

    __table_args__ = (
        CheckConstraint(
            "source_type IN ('synthetic', 'real', 'derived')",
            name="ck_import_batch_source_type_valid",
        ),
    )

    def __repr__(self) -> str:
        label = "DEMO" if self.is_demo else "REAL"
        return f"<ImportBatch {self.id} [{label}] {self.source_file} @ {self.import_timestamp}>"


# ─────────────────────────────────────────────────────────────────────────────
# Machine master
# ─────────────────────────────────────────────────────────────────────────────

class Machine(Base):
    """
    One row per physical (or synthetic) machine.

    The granularity column is the key provenance marker:
      - real_grounded: the machine number exists in the real daily reports.
      - synthetic_loom_number: the number was invented; real reports only
        show brand-level weaving totals.
    """

    __tablename__ = "machines"

    machine_id: str = Column(String(20), primary_key=True, comment="e.g. TOY-01, RF-06, VTX-12")
    unit: str = Column(String(50), nullable=False, comment="e.g. Unit I")
    department: str = Column(String(50), nullable=False, comment="Weaving | Spinning | Preparatory")
    machine_type: str = Column(String(50), nullable=False)
    granularity: str = Column(
        String(50),
        nullable=False,
        comment="real_grounded | synthetic_loom_number",
    )
    source_type: str = Column(
        String(20),
        nullable=False,
        default="synthetic",
        comment="synthetic | real | derived",
    )
    active: bool = Column(Boolean, nullable=False, default=True)
    created_at: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    production_logs = relationship("ProductionLog", back_populates="machine", lazy="dynamic")
    breakdown_events = relationship("BreakdownEvent", back_populates="machine", lazy="dynamic")
    revenue_logs = relationship("RevenueLog", back_populates="machine", lazy="dynamic")

    __table_args__ = (
        CheckConstraint(
            "granularity IN ('real_grounded', 'synthetic_loom_number')",
            name="ck_machine_granularity_valid",
        ),
        CheckConstraint(
            "source_type IN ('synthetic', 'real', 'derived')",
            name="ck_machine_source_type_valid",
        ),
    )

    def __repr__(self) -> str:
        return f"<Machine {self.machine_id} ({self.machine_type}, {self.department})>"


# ─────────────────────────────────────────────────────────────────────────────
# Production Log
# ─────────────────────────────────────────────────────────────────────────────

class ProductionLog(Base):
    """
    One record = one machine × one date × one shift.

    Unique constraint on (machine_id, date, shift) enforces that there can
    never be two conflicting production entries for the same machine-shift.
    """

    __tablename__ = "production_logs"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, comment="Production date (not import date)")
    shift: int = Column(SmallInteger, nullable=False, comment="1 | 2 | 3")
    machine_id: str = Column(
        String(20),
        ForeignKey("machines.machine_id", ondelete="RESTRICT"),
        nullable=False,
    )
    target_qty = Column(Numeric(14, 2), nullable=False, comment="Target quantity for this shift")
    actual_qty = Column(Numeric(14, 2), nullable=False, comment="Actual quantity produced")
    efficiency_pct = Column(Numeric(6, 2), nullable=False, comment="actual / target × 100")
    import_batch_id: int = Column(
        Integer,
        ForeignKey("import_batches.id", ondelete="SET NULL"),
        nullable=True,
        comment="NULL for rows imported before Phase 2",
    )
    created_at: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    machine = relationship("Machine", back_populates="production_logs")
    import_batch = relationship("ImportBatch")

    __table_args__ = (
        UniqueConstraint(
            "machine_id", "date", "shift",
            name="uq_production_machine_date_shift",
        ),
        CheckConstraint("shift IN (1, 2, 3)", name="ck_production_shift_valid"),
        CheckConstraint("target_qty >= 0", name="ck_production_target_nonneg"),
        CheckConstraint("actual_qty >= 0", name="ck_production_actual_nonneg"),
        CheckConstraint(
            "efficiency_pct >= 0 AND efficiency_pct <= 110",
            name="ck_production_efficiency_range",
        ),
        Index("ix_production_date", "date"),
        Index("ix_production_machine_id", "machine_id"),
        Index("ix_production_date_machine", "date", "machine_id"),
    )

    def __repr__(self) -> str:
        return f"<ProductionLog {self.machine_id} {self.date} S{self.shift}>"


# ─────────────────────────────────────────────────────────────────────────────
# Breakdown Event
# ─────────────────────────────────────────────────────────────────────────────

class BreakdownEvent(Base):
    """
    One record = one breakdown event on one machine in one shift.

    IMPORTANT: There is NO unique constraint on (machine_id, date, shift).
    A machine can have multiple breakdown events in a single shift.
    """

    __tablename__ = "breakdown_events"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False)
    shift: int = Column(SmallInteger, nullable=False, comment="1 | 2 | 3")
    machine_id: str = Column(
        String(20),
        ForeignKey("machines.machine_id", ondelete="RESTRICT"),
        nullable=False,
    )
    reason: str = Column(String(200), nullable=False)
    duration_minutes: int = Column(Integer, nullable=False, comment="Downtime in minutes (> 0)")
    source_type: str = Column(String(20), nullable=False, default="synthetic")
    import_batch_id: int = Column(
        Integer,
        ForeignKey("import_batches.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    machine = relationship("Machine", back_populates="breakdown_events")
    import_batch = relationship("ImportBatch")

    __table_args__ = (
        CheckConstraint("shift IN (1, 2, 3)", name="ck_breakdown_shift_valid"),
        CheckConstraint("duration_minutes > 0", name="ck_breakdown_duration_positive"),
        CheckConstraint(
            "source_type IN ('synthetic', 'real', 'derived')",
            name="ck_breakdown_source_type_valid",
        ),
        Index("ix_breakdown_date", "date"),
        Index("ix_breakdown_machine_id", "machine_id"),
        Index("ix_breakdown_date_machine", "date", "machine_id"),
        Index("ix_breakdown_reason", "reason"),
    )

    def __repr__(self) -> str:
        return f"<BreakdownEvent {self.machine_id} {self.date} S{self.shift} {self.reason[:30]}>"


# ─────────────────────────────────────────────────────────────────────────────
# Revenue Log
# ─────────────────────────────────────────────────────────────────────────────

class RevenueLog(Base):
    """
    One record = one fabric-style revenue contribution from one machine on one shift.

    Revenue is only available for Weaving machines in V1.
    source_type defaults to 'derived' because V1 revenue is computed from
    actual_qty × fabric_rate, not read from a real revenue report.
    """

    __tablename__ = "revenue_logs"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False)
    shift: int = Column(SmallInteger, nullable=False, comment="1 | 2 | 3")
    machine_id: str = Column(
        String(20),
        ForeignKey("machines.machine_id", ondelete="RESTRICT"),
        nullable=False,
    )
    fabric_style: str = Column(String(100), nullable=False)
    revenue = Column(Numeric(14, 4), nullable=False, comment="Revenue in Indian Rupees (Rs)")
    source_type: str = Column(String(20), nullable=False, default="derived")
    import_batch_id: int = Column(
        Integer,
        ForeignKey("import_batches.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    machine = relationship("Machine", back_populates="revenue_logs")
    import_batch = relationship("ImportBatch")

    __table_args__ = (
        CheckConstraint("shift IN (1, 2, 3)", name="ck_revenue_shift_valid"),
        CheckConstraint("revenue >= 0", name="ck_revenue_nonneg"),
        CheckConstraint(
            "source_type IN ('synthetic', 'real', 'derived')",
            name="ck_revenue_source_type_valid",
        ),
        Index("ix_revenue_date", "date"),
        Index("ix_revenue_machine_id", "machine_id"),
        Index("ix_revenue_date_machine", "date", "machine_id"),
        Index("ix_revenue_fabric_style", "fabric_style"),
    )

    def __repr__(self) -> str:
        return f"<RevenueLog {self.machine_id} {self.date} S{self.shift} {self.fabric_style}>"
