"""
Loom AI — SQLAlchemy ORM models (V1).

Design principles
-----------------
1. PROVENANCE FIRST: every fact table carries source_type so the UI can
   always tell a manager whether a number came from real data, derived
   calculation, or synthetic generation.

2. EXTENSIBILITY: every future table (AttendanceLog, QualityLog, etc.)
   hangs off Machine using the same machine_id + date + shift grain.
   Nothing here needs to change to add Q2–Q23.

3. CONSTRAINTS IN THE DB: uniqueness, range checks, and foreign keys are
   enforced at the database level, not just at the application level.
   This means a bulk INSERT from any tool will still fail on bad data.

4. NUMERIC PRECISION: revenue and quantities use Numeric (fixed-point),
   not Float, to avoid floating-point rounding surprises in financial totals.

Granularity values (preserved from source CSV)
----------------------------------------------
  real_grounded          - machine number corresponds to a real physical machine
  synthetic_loom_number  - loom number was invented; real reports show brand totals only

Source type values
------------------
  synthetic  - generated by the synthetic data generator
  real       - imported from actual company records
  derived    - calculated from other records (e.g. revenue = qty × rate)
"""
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


# ─────────────────────────────────────────────────────────────────────────────
# Machine master
# ─────────────────────────────────────────────────────────────────────────────

class Machine(Base):
    """
    One row per physical (or synthetic) machine.

    This is the anchor entity.  Every fact table (ProductionLog,
    BreakdownEvent, RevenueLog, and future tables) references machine_id.

    The granularity column is the key provenance marker:
      - real_grounded: the machine number exists in the real daily reports.
      - synthetic_loom_number: the number was invented; real reports only
        show brand-level weaving totals.
    """

    __tablename__ = "machines"

    machine_id: str = Column(String(20), primary_key=True, comment="e.g. TOY-01, RF-06, VTX-12")
    unit: str = Column(String(50), nullable=False, comment="e.g. Unit I")
    department: str = Column(String(50), nullable=False, comment="Weaving | Spinning | Preparatory")
    machine_type: str = Column(String(50), nullable=False, comment="Toyota | Tsudakoma | RingFrame | Vortex | Airjet | Sulzer")
    granularity: str = Column(
        String(50),
        nullable=False,
        comment="real_grounded | synthetic_loom_number",
    )
    source_type: str = Column(
        String(20),
        nullable=False,
        default="synthetic",
        comment="synthetic | real | derived",
    )
    active: bool = Column(Boolean, nullable=False, default=True, comment="False = decommissioned")
    created_at: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # Relationships — back-populated for ORM convenience
    production_logs = relationship("ProductionLog", back_populates="machine", lazy="dynamic")
    breakdown_events = relationship("BreakdownEvent", back_populates="machine", lazy="dynamic")
    revenue_logs = relationship("RevenueLog", back_populates="machine", lazy="dynamic")

    __table_args__ = (
        CheckConstraint(
            "granularity IN ('real_grounded', 'synthetic_loom_number')",
            name="ck_machine_granularity_valid",
        ),
        CheckConstraint(
            "source_type IN ('synthetic', 'real', 'derived')",
            name="ck_machine_source_type_valid",
        ),
    )

    def __repr__(self) -> str:
        return f"<Machine {self.machine_id} ({self.machine_type}, {self.department})>"


# ─────────────────────────────────────────────────────────────────────────────
# Production Log
# ─────────────────────────────────────────────────────────────────────────────

class ProductionLog(Base):
    """
    One record = one machine × one date × one shift.

    Unique constraint on (machine_id, date, shift) enforces that there can
    never be two conflicting production entries for the same machine-shift.

    Quantities are stored as Numeric(14, 2) to support both grams/metres
    (small numbers) and total-mill-day figures (large numbers) without loss.
    """

    __tablename__ = "production_logs"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, comment="Production date (not import date)")
    shift: int = Column(SmallInteger, nullable=False, comment="1 | 2 | 3")
    machine_id: str = Column(
        String(20),
        ForeignKey("machines.machine_id", ondelete="RESTRICT"),
        nullable=False,
    )
    target_qty = Column(Numeric(14, 2), nullable=False, comment="Target quantity for this shift")
    actual_qty = Column(Numeric(14, 2), nullable=False, comment="Actual quantity produced")
    efficiency_pct = Column(Numeric(6, 2), nullable=False, comment="actual / target × 100")
    created_at: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    machine = relationship("Machine", back_populates="production_logs")

    __table_args__ = (
        # Core business constraint: one row per machine-date-shift.
        UniqueConstraint(
            "machine_id", "date", "shift",
            name="uq_production_machine_date_shift",
        ),
        # Database-enforced range checks.
        CheckConstraint("shift IN (1, 2, 3)", name="ck_production_shift_valid"),
        CheckConstraint("target_qty > 0", name="ck_production_target_positive"),
        CheckConstraint("actual_qty >= 0", name="ck_production_actual_nonneg"),
        CheckConstraint(
            "efficiency_pct >= 0 AND efficiency_pct <= 110",
            name="ck_production_efficiency_range",
        ),
        # Query-path indexes.
        Index("ix_production_date", "date"),
        Index("ix_production_machine_id", "machine_id"),
        Index("ix_production_date_machine", "date", "machine_id"),
    )

    def __repr__(self) -> str:
        return f"<ProductionLog {self.machine_id} {self.date} S{self.shift}>"


# ─────────────────────────────────────────────────────────────────────────────
# Breakdown Event
# ─────────────────────────────────────────────────────────────────────────────

class BreakdownEvent(Base):
    """
    One record = one breakdown event on one machine in one shift.

    IMPORTANT: There is NO unique constraint on (machine_id, date, shift).
    A machine can have multiple breakdown events in a single shift.
    E.g. a loom might stop for a weft break and then for a voltage fluctuation
    in the same 8-hour shift.

    The reason column is kept as free text to match the verbatim vocabulary
    from the real daily reports' remarks columns.
    """

    __tablename__ = "breakdown_events"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, comment="Date of breakdown")
    shift: int = Column(SmallInteger, nullable=False, comment="1 | 2 | 3")
    machine_id: str = Column(
        String(20),
        ForeignKey("machines.machine_id", ondelete="RESTRICT"),
        nullable=False,
    )
    reason: str = Column(
        String(200),
        nullable=False,
        comment="Verbatim-in-spirit from actual report remarks columns",
    )
    duration_minutes: int = Column(Integer, nullable=False, comment="Downtime in minutes (> 0)")
    source_type: str = Column(
        String(20),
        nullable=False,
        default="synthetic",
        comment="synthetic | real | derived",
    )
    created_at: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    machine = relationship("Machine", back_populates="breakdown_events")

    __table_args__ = (
        CheckConstraint("shift IN (1, 2, 3)", name="ck_breakdown_shift_valid"),
        CheckConstraint("duration_minutes > 0", name="ck_breakdown_duration_positive"),
        CheckConstraint(
            "source_type IN ('synthetic', 'real', 'derived')",
            name="ck_breakdown_source_type_valid",
        ),
        Index("ix_breakdown_date", "date"),
        Index("ix_breakdown_machine_id", "machine_id"),
        Index("ix_breakdown_date_machine", "date", "machine_id"),
        Index("ix_breakdown_reason", "reason"),
    )

    def __repr__(self) -> str:
        return f"<BreakdownEvent {self.machine_id} {self.date} S{self.shift} {self.reason[:30]}>"


# ─────────────────────────────────────────────────────────────────────────────
# Revenue Log
# ─────────────────────────────────────────────────────────────────────────────

class RevenueLog(Base):
    """
    One record = one fabric-style's revenue contribution from one machine on
    one shift.

    Design notes
    ------------
    - Revenue is only available for Weaving machines in V1. The department
      filter is applied in the analytics layer, not here, to keep the model
      general.
    - Multiple fabric styles can appear for the same machine-date-shift
      (a loom can switch styles mid-shift, or run a blend). No unique
      constraint is applied on (machine_id, date, shift).
    - source_type defaults to 'derived' because V1 revenue is computed from
      actual_qty × fabric_rate, not read from a real revenue report.
    - Numeric(14, 4) allows up to Rs 9,999,999,999.9999 with 4 decimal
      places — appropriate for per-shift contributions and cumulative MTD.
    """

    __tablename__ = "revenue_logs"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, comment="Revenue date")
    shift: int = Column(SmallInteger, nullable=False, comment="1 | 2 | 3")
    machine_id: str = Column(
        String(20),
        ForeignKey("machines.machine_id", ondelete="RESTRICT"),
        nullable=False,
    )
    fabric_style: str = Column(
        String(100),
        nullable=False,
        comment="e.g. Excel Slub, Liveaco Compact, VSF Export",
    )
    revenue = Column(
        Numeric(14, 4),
        nullable=False,
        comment="Revenue in Indian Rupees (Rs)",
    )
    source_type: str = Column(
        String(20),
        nullable=False,
        default="derived",
        comment="derived = computed from actual_qty × fabric_rate; real = actual invoice",
    )
    created_at: datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    machine = relationship("Machine", back_populates="revenue_logs")

    __table_args__ = (
        CheckConstraint("shift IN (1, 2, 3)", name="ck_revenue_shift_valid"),
        CheckConstraint("revenue >= 0", name="ck_revenue_nonneg"),
        CheckConstraint(
            "source_type IN ('synthetic', 'real', 'derived')",
            name="ck_revenue_source_type_valid",
        ),
        Index("ix_revenue_date", "date"),
        Index("ix_revenue_machine_id", "machine_id"),
        Index("ix_revenue_date_machine", "date", "machine_id"),
        Index("ix_revenue_fabric_style", "fabric_style"),
    )

    def __repr__(self) -> str:
        return f"<RevenueLog {self.machine_id} {self.date} S{self.shift} {self.fabric_style}>"
