"""v2 initial schema

Revision ID: 65aaf397533a
Revises: 
Create Date: 2026-09-01 11:03:39.558249
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '65aaf397533a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loom_type',
    sa.Column('loom_type_code', sa.String(length=10), nullable=False),
    sa.Column('make', sa.Enum('TSUDAKOMA', 'SULZER', name='loom_make'), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('loom_type_code')
    )
    op.create_table('reason_code',
    sa.Column('reason_code_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label_en', sa.String(length=150), nullable=False),
    sa.Column('label_ta', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('MECHANICAL', 'ELECTRICAL', 'MATERIAL', 'MANPOWER', 'PLANNED', 'UTILITY', 'QUALITY', 'OTHER', name='reason_category'), nullable=False),
    sa.PrimaryKeyConstraint('reason_code_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('shift_master',
    sa.Column('shift_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('scheduled_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shift_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('unit',
    sa.Column('unit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_own_unit', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'pm', 'supervisor', 'vendor_coordinator', name='user_role'), nullable=False),
    sa.Column('language_pref', sa.String(length=5), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('cost_master',
    sa.Column('cost_master_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('rate_per_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yarn_rate_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('CONFIRMED', 'ESTIMATED', name='cost_rate_source'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ),
    sa.PrimaryKeyConstraint('cost_master_id')
    )
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('WEAVER', 'TRAINING_WEAVER', 'FABRIC_CHECKER', 'LOADMAN', 'SHIFT_FITTER', 'HEAD_FITTER', 'KNOTTER', 'GAITER', 'ELECTRICIAN', 'OILER', 'QUALITY_CHECKER', 'SWEEPER', 'OTHER', name='employee_role'), nullable=False),
    sa.Column('grade', sa.Enum('G1', 'G1_PLUS', 'G2', 'G2_PLUS', 'G3', 'G3_PLUS', 'G4', 'G5', 'G6', 'G6_PLUS', name='employee_grade'), nullable=True),
    sa.Column('std_looms', sa.Integer(), nullable=True),
    sa.Column('std_efficiency_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('DEMO', 'CSV_IMPORT', 'MANUAL_ENTRY', 'CONTROLLER_FEED', name='data_source'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index('ix_employee_unit_role', 'employee', ['unit_id', 'role'], unique=False)
    op.create_table('import_batch',
    sa.Column('import_batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ),
    sa.PrimaryKeyConstraint('import_batch_id')
    )
    op.create_table('shed',
    sa.Column('shed_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('shed_id'),
    sa.UniqueConstraint('unit_id', 'code', name='uq_shed_unit_code')
    )
    op.create_table('style',
    sa.Column('style_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_code', sa.String(length=150), nullable=False),
    sa.Column('loom_type_code', sa.String(length=10), nullable=True),
    sa.Column('warp_ends', sa.Integer(), nullable=False),
    sa.Column('reed_pick', sa.String(length=30), nullable=True),
    sa.Column('width_inch', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weave_construction', sa.String(length=30), nullable=True),
    sa.Column('picks_per_metre', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('std_crimp_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('std_rpm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('std_efficiency_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('revenue_per_metre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revenue_rate_source', sa.Enum('CONFIRMED', 'ESTIMATED', name='rate_source'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['loom_type_code'], ['loom_type.loom_type_code'], ),
    sa.PrimaryKeyConstraint('style_id'),
    sa.UniqueConstraint('style_code')
    )
    op.create_table('user_unit_scope',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'unit_id')
    )
    op.create_table('vendor_unit_monthly_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('efficiency_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('kilo_picks_day_avg', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('metres_day_avg', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('warp_breaks_per_hr', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('weft_breaks_per_hr', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('month_kilo_picks', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('month_metres', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('month_rolls', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'month', name='uq_vendor_summary_unit_month')
    )
    op.create_table('loom',
    sa.Column('loom_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('shed_id', sa.Integer(), nullable=True),
    sa.Column('loom_no', sa.String(length=30), nullable=False),
    sa.Column('loom_type_code', sa.String(length=10), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('register_confirmed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('DEMO', 'CSV_IMPORT', 'MANUAL_ENTRY', 'CONTROLLER_FEED', name='loom_data_source'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loom_type_code'], ['loom_type.loom_type_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shed_id'], ['shed.shed_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('loom_id'),
    sa.UniqueConstraint('unit_id', 'loom_no', name='uq_loom_unit_no')
    )
    op.create_index('ix_loom_unit_active', 'loom', ['unit_id', 'active'], unique=False)
    op.create_table('style_unit_crimp_monthly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('crimp_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source', sa.Enum('CONFIRMED', 'ESTIMATED', name='crimp_rate_source'), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['style.style_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'unit_id', 'month', name='uq_style_unit_crimp_month')
    )
    op.create_table('assignment',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('DEMO', 'CSV_IMPORT', 'MANUAL_ENTRY', 'CONTROLLER_FEED', name='assignment_data_source'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loom_id'], ['loom.loom_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.shift_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('loom_id', 'shift_id', 'work_date', name='uq_assignment_loom_shift_date')
    )
    op.create_table('beam_run',
    sa.Column('beam_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('DEMO', 'CSV_IMPORT', 'MANUAL_ENTRY', 'CONTROLLER_FEED', name='beam_data_source'), nullable=False),
    sa.ForeignKeyConstraint(['loom_id'], ['loom.loom_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['style_id'], ['style.style_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('beam_run_id')
    )
    op.create_index('ix_beam_run_loom_time', 'beam_run', ['loom_id', 'started_at'], unique=False)
    op.create_table('fabric_roll',
    sa.Column('roll_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('metres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('doffed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('DEMO', 'CSV_IMPORT', 'MANUAL_ENTRY', 'CONTROLLER_FEED', name='roll_data_source'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('metres >= 0', name='ck_roll_metres_nonneg'),
    sa.ForeignKeyConstraint(['loom_id'], ['loom.loom_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.shift_id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.style_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('roll_id')
    )
    op.create_index('ix_roll_loom_date', 'fabric_roll', ['loom_id', 'work_date'], unique=False)
    op.create_table('production_target',
    sa.Column('target_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('available_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_metres', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('target_kilo_picks', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('target_efficiency_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('basis_note', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('DEMO', 'CSV_IMPORT', 'MANUAL_ENTRY', 'CONTROLLER_FEED', name='target_data_source'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loom_id'], ['loom.loom_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.shift_id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.style_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('target_id'),
    sa.UniqueConstraint('loom_id', 'work_date', 'shift_id', name='uq_target_loom_date_shift')
    )
    op.create_index('ix_target_unit_date', 'production_target', ['unit_id', 'work_date'], unique=False)
    op.create_table('stop_event',
    sa.Column('stop_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attending_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_code_id', sa.Integer(), nullable=True),
    sa.Column('raw_remark', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RAISED', 'ACKNOWLEDGED', 'ATTENDING', 'RESOLVED', name='stop_status'), nullable=False),
    sa.Column('raised_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('DEMO', 'CSV_IMPORT', 'MANUAL_ENTRY', 'CONTROLLER_FEED', name='stopevent_data_source'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(acknowledged_at IS NULL OR acknowledged_at >= raised_at) AND (attending_at IS NULL OR acknowledged_at IS NULL OR attending_at >= acknowledged_at) AND (resolved_at IS NULL OR attending_at IS NULL OR resolved_at >= attending_at)', name='ck_stop_lifecycle_order'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.import_batch_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loom_id'], ['loom.loom_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reason_code_id'], ['reason_code.reason_code_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.shift_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stop_event_id')
    )
    op.create_index('ix_stopevent_loom_date', 'stop_event', ['loom_id', 'work_date'], unique=False)
    op.create_index('ix_stopevent_reason', 'stop_event', ['reason_code_id'], unique=False)
    op.create_table('suggestion_log',
    sa.Column('suggestion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('rupee_impact', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKED', 'DISMISSED', 'DONE', name='suggestion_status'), nullable=False),
    sa.Column('acted_by', sa.String(length=100), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['loom_id'], ['loom.loom_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.shift_id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.style_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    op.create_index('ix_suggestion_rule', 'suggestion_log', ['rule_code'], unique=False)
    op.create_index('ix_suggestion_unit_date', 'suggestion_log', ['unit_id', 'work_date'], unique=False)
    op.create_table('production_log',
    sa.Column('production_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False, comment='Calendar date the SHIFT STARTED'),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('beam_run_id', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_minutes', sa.Integer(), nullable=False),
    sa.Column('running_minutes', sa.Integer(), nullable=False),
    sa.Column('std_rpm_snapshot', sa.Numeric(precision=8, scale=2), nullable=False, comment='style.std_rpm frozen at run time'),
    sa.Column('actual_picks', sa.BigInteger(), nullable=False),
    sa.Column('metres', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('kilo_picks', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('warp_breaks', sa.Integer(), nullable=False),
    sa.Column('weft_breaks', sa.Integer(), nullable=False),
    sa.Column('actual_crimp_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='NULL until lab feed exists (Q18-Q20 BLOCKED)'),
    sa.Column('source', sa.Enum('DEMO', 'CSV_IMPORT', 'MANUAL_ENTRY', 'CONTROLLER_FEED', name='prodlog_data_source'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('metres >= 0 AND kilo_picks >= 0 AND actual_picks >= 0', name='ck_prodlog_nonneg'),
    sa.CheckConstraint('running_minutes <= scheduled_minutes', name='ck_prodlog_running_le_scheduled'),
    sa.CheckConstraint('warp_breaks >= 0 AND weft_breaks >= 0', name='ck_prodlog_breaks_nonneg'),
    sa.ForeignKeyConstraint(['beam_run_id'], ['beam_run.beam_run_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.import_batch_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loom_id'], ['loom.loom_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.shift_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['style_id'], ['style.style_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('production_log_id'),
    sa.UniqueConstraint('loom_id', 'work_date', 'shift_id', name='uq_prodlog_loom_date_shift')
    )
    op.create_index('ix_prodlog_date_loom', 'production_log', ['work_date', 'loom_id'], unique=False)
    op.create_index('ix_prodlog_employee', 'production_log', ['employee_id'], unique=False)
    op.create_index('ix_prodlog_style', 'production_log', ['style_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prodlog_style', table_name='production_log')
    op.drop_index('ix_prodlog_employee', table_name='production_log')
    op.drop_index('ix_prodlog_date_loom', table_name='production_log')
    op.drop_table('production_log')
    op.drop_index('ix_suggestion_unit_date', table_name='suggestion_log')
    op.drop_index('ix_suggestion_rule', table_name='suggestion_log')
    op.drop_table('suggestion_log')
    op.drop_index('ix_stopevent_reason', table_name='stop_event')
    op.drop_index('ix_stopevent_loom_date', table_name='stop_event')
    op.drop_table('stop_event')
    op.drop_index('ix_target_unit_date', table_name='production_target')
    op.drop_table('production_target')
    op.drop_index('ix_roll_loom_date', table_name='fabric_roll')
    op.drop_table('fabric_roll')
    op.drop_index('ix_beam_run_loom_time', table_name='beam_run')
    op.drop_table('beam_run')
    op.drop_table('assignment')
    op.drop_table('style_unit_crimp_monthly')
    op.drop_index('ix_loom_unit_active', table_name='loom')
    op.drop_table('loom')
    op.drop_table('vendor_unit_monthly_summary')
    op.drop_table('user_unit_scope')
    op.drop_table('style')
    op.drop_table('shed')
    op.drop_table('import_batch')
    op.drop_index('ix_employee_unit_role', table_name='employee')
    op.drop_table('employee')
    op.drop_table('cost_master')
    op.drop_table('audit_log')
    op.drop_table('user_account')
    op.drop_table('unit')
    op.drop_table('shift_master')
    op.drop_table('reason_code')
    op.drop_table('loom_type')
    # ### end Alembic commands ###

    # Postgres ENUM types are separate objects from the tables that use
    # them — dropping the tables above does not drop the types, so a
    # second alembic upgrade/downgrade cycle fails with "type already
    # exists" (found by running upgrade -> downgrade -> upgrade as a
    # symmetry check, per docs/V2_DESIGN.md task 0.2 DoD). Drop them all
    # explicitly, checkfirst so this stays safe to re-run.
    bind = op.get_bind()
    for enum_name in (
        "loom_make", "reason_category", "user_role", "cost_rate_source",
        "employee_role", "employee_grade", "data_source", "rate_source",
        "loom_data_source", "crimp_rate_source", "assignment_data_source",
        "beam_data_source", "roll_data_source", "target_data_source",
        "stop_status", "stopevent_data_source", "confidence_level",
        "suggestion_status", "prodlog_data_source",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
